# Generated by Django 5.2.1 on 2025-05-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='description_en',
            new_name='content_en',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='description_ru',
            new_name='content_ru',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='description_uz',
            new_name='content_uz',
        ),
    ]
