# Generated by Django 5.2.1 on 2025-06-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_banner_unique_together_and_more'),
        ('news', '0002_rename_description_news_content_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('school', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='news',
            unique_together={('school', 'slug')},
        ),
    ]
