# Generated by Django 5.2.1 on 2025-06-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_banner_unique_together_and_more'),
        ('news', '0003_alter_category_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='news',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('school', 'slug'), name='unique_newscategory_school_slug'),
        ),
        migrations.AddConstraint(
            model_name='news',
            constraint=models.UniqueConstraint(fields=('school', 'slug'), name='unique_news_school_slug'),
        ),
    ]
