# Generated by Django 5.2.1 on 2025-07-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cultureart',
            options={'verbose_name': "Madaniy san'at", 'verbose_name_plural': "Madaniy san'at"},
        ),
        migrations.AlterModelOptions(
            name='fineart',
            options={'verbose_name': "Tasviriy san'at", 'verbose_name_plural': "Tasviriy san'at"},
        ),
    ]
