# Generated by Django 5.2.1 on 2025-06-01 07:13

import apps.common.utils
import apps.common.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0019_alter_faq_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('file', models.FileField(help_text="Fayl 5 MB dan katta bo'lishi mumkin emas.", upload_to=apps.common.utils.generate_upload_path, validators=[apps.common.validators.file_size], verbose_name='Fayl')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Yuklab olishlar soni')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_files', to='main.school', verbose_name='Maktab')),
            ],
            options={
                'verbose_name': 'Resurs fayl ',
                'verbose_name_plural': 'Resurs fayllar',
            },
        ),
        migrations.CreateModel(
            name='ResourceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('youtube_link', models.URLField(validators=[apps.common.validators.validate_youtube_link], verbose_name='Youtube havola')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_videos', to='main.school', verbose_name='Maktab')),
            ],
            options={
                'verbose_name': 'Resurs video ',
                'verbose_name_plural': 'Resurs videolar',
            },
        ),
    ]
