# Generated by Django 5.2.1 on 2025-06-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_banner_unique_together_and_more'),
        ('resource', '0002_alter_resourcefile_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resourcefile',
            unique_together={('school', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='resourcevideo',
            unique_together={('school', 'title')},
        ),
    ]
