# Generated by Django 5.2.1 on 2025-06-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_banner_unique_together_and_more'),
        ('resource', '0003_alter_resourcefile_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resourcefile',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='resourcevideo',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='resourcefile',
            constraint=models.UniqueConstraint(fields=('school', 'title'), name='unique_resourcefile_school_title'),
        ),
        migrations.AddConstraint(
            model_name='resourcefile',
            constraint=models.UniqueConstraint(fields=('school', 'title_uz'), name='unique_resourcefile_school_title-title_uz'),
        ),
        migrations.AddConstraint(
            model_name='resourcefile',
            constraint=models.UniqueConstraint(fields=('school', 'title_ru'), name='unique_resourcefile_school_title-title_ru'),
        ),
        migrations.AddConstraint(
            model_name='resourcefile',
            constraint=models.UniqueConstraint(fields=('school', 'title_en'), name='unique_resourcefile_school_title-title_en'),
        ),
        migrations.AddConstraint(
            model_name='resourcevideo',
            constraint=models.UniqueConstraint(fields=('school', 'title'), name='unique_resourcevideo_school_title'),
        ),
        migrations.AddConstraint(
            model_name='resourcevideo',
            constraint=models.UniqueConstraint(fields=('school', 'title_uz'), name='unique_resourcevideo_school_title-title_uz'),
        ),
        migrations.AddConstraint(
            model_name='resourcevideo',
            constraint=models.UniqueConstraint(fields=('school', 'title_ru'), name='unique_resourcevideo_school_title-title_ru'),
        ),
        migrations.AddConstraint(
            model_name='resourcevideo',
            constraint=models.UniqueConstraint(fields=('school', 'title_en'), name='unique_resourcevideo_school_title-title_en'),
        ),
    ]
