# Generated by Django 5.2.1 on 2025-06-04 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_alter_resourcefile_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resourcefile',
            name='unique_resourcefile_school_title',
        ),
        migrations.RemoveConstraint(
            model_name='resourcefile',
            name='unique_resourcefile_school_title-title_uz',
        ),
        migrations.RemoveConstraint(
            model_name='resourcefile',
            name='unique_resourcefile_school_title-title_ru',
        ),
        migrations.RemoveConstraint(
            model_name='resourcefile',
            name='unique_resourcefile_school_title-title_en',
        ),
        migrations.RemoveConstraint(
            model_name='resourcevideo',
            name='unique_resourcevideo_school_title',
        ),
        migrations.RemoveConstraint(
            model_name='resourcevideo',
            name='unique_resourcevideo_school_title-title_uz',
        ),
        migrations.RemoveConstraint(
            model_name='resourcevideo',
            name='unique_resourcevideo_school_title-title_ru',
        ),
        migrations.RemoveConstraint(
            model_name='resourcevideo',
            name='unique_resourcevideo_school_title-title_en',
        ),
    ]
