# Generated by Django 5.2.1 on 2025-05-27 07:06

import apps.common.utils
import apps.common.validators
import apps.media.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0008_direction_directionschool'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('youtube_link', models.URLField(validators=[apps.media.models.validate_youtube_link], verbose_name='Youtube havola')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videolar',
            },
        ),
        migrations.CreateModel(
            name='MediaCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_collections', to='main.school', verbose_name='Maktab')),
            ],
            options={
                'verbose_name': 'Kolleksiya',
                'verbose_name_plural': 'Kolleksiyalar',
            },
        ),
        migrations.CreateModel(
            name='MediaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('show_in_main', models.BooleanField(default=False, verbose_name="Asosiy sahifada ko'rsatish")),
                ('image', models.ImageField(help_text="Rasm 5 MB dan katta bo'lishi mumkin emas.", upload_to=apps.common.utils.generate_upload_path, validators=[apps.common.validators.file_size], verbose_name='Rasm')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_images', to='media.mediacollection', verbose_name='Kolleksiya')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
