# Generated by Django 5.2.1 on 2025-05-27 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediacollection',
            options={'verbose_name': "Rasmlar to'plami ", 'verbose_name_plural': "Rasmlar to'plami"},
        ),
        migrations.AlterField(
            model_name='mediaimage',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_images', to='media.mediacollection', verbose_name="Rasmlar to'plami"),
        ),
    ]
