# Generated by Django 5.2.1 on 2025-05-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_mediacollection_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaimage',
            name='title',
        ),
        migrations.AddField(
            model_name='mediacollection',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='mediacollection',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='mediacollection',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='mediavideo',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='mediavideo',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='mediavideo',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
    ]
