# Generated by Django 5.2.1 on 2025-05-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_remove_mediaimage_title_mediacollection_title_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaimage',
            options={'verbose_name': 'Rasm ', 'verbose_name_plural': 'Rasmlar'},
        ),
        migrations.AlterModelOptions(
            name='mediavideo',
            options={'verbose_name': 'Video ', 'verbose_name_plural': 'Videolar'},
        ),
    ]
