# Generated by Django 5.2.1 on 2025-05-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_alter_mediaimage_options_alter_mediavideo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacollection',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
