# Generated by Django 5.2.1 on 2025-06-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_banner_unique_together_and_more'),
        ('media', '0005_mediacollection_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mediacollection',
            unique_together={('school', 'slug')},
        ),
    ]
