# Generated by Django 5.2.1 on 2025-06-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_banner_unique_together_and_more'),
        ('media', '0006_alter_mediacollection_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mediacollection',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='mediacollection',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AddConstraint(
            model_name='mediacollection',
            constraint=models.UniqueConstraint(fields=('school', 'slug'), name='unique_mediacollection_school_slug'),
        ),
    ]
