# Generated by Django 5.2.1 on 2025-05-20 11:00

import apps.common.mixins
import django.db.models.deletion
import mptt.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('domain', models.SlugField(unique=True, verbose_name='Subdomen')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Tafsilot')),
                ('description_uz', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Tafsilot')),
                ('description_ru', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Tafsilot')),
                ('description_en', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Tafsilot')),
                ('short_description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Qisqacha tafsilot')),
                ('short_description_uz', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Qisqacha tafsilot')),
                ('short_description_ru', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Qisqacha tafsilot')),
                ('short_description_en', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Qisqacha tafsilot')),
                ('founded_year', models.SmallIntegerField(blank=True, null=True, verbose_name='Ishga tushgan yili')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name="O'quvchilar sig'imi")),
                ('student_count', models.PositiveIntegerField(blank=True, null=True, verbose_name="O'quvchilar soni")),
                ('teacher_count', models.PositiveIntegerField(blank=True, null=True, verbose_name="O'qituvchilar soni")),
                ('direction_count', models.PositiveIntegerField(blank=True, null=True, verbose_name="Yo'nalishlar soni")),
                ('class_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sinflar soni')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon raqami')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil')),
                ('address_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil')),
                ('address_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil')),
                ('address_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Longitude')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='Instagram link')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Telegram link')),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='Facebook link')),
                ('youtube_link', models.URLField(blank=True, null=True, verbose_name='Youtube link')),
            ],
            options={
                'verbose_name': 'Maktab',
                'verbose_name_plural': 'Maktablar',
            },
            bases=(apps.common.mixins.SlugifyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('title_uz', models.CharField(max_length=120, null=True)),
                ('title_ru', models.CharField(max_length=120, null=True)),
                ('title_en', models.CharField(max_length=120, null=True)),
                ('url', models.CharField(max_length=255)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.menu')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Rasm')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('button_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tugma matni')),
                ('button_text_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tugma matni')),
                ('button_text_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tugma matni')),
                ('button_text_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tugma matni')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Havola')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='main.school', verbose_name='Maktab')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
            },
        ),
        migrations.CreateModel(
            name='SchoolLife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('image', models.ImageField(upload_to='school_lives/', verbose_name='Rasm')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Tafsilot')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_lives', to='main.school', verbose_name='Maktab')),
            ],
            options={
                'verbose_name': 'Maktab hayoti',
                'verbose_name_plural': 'Maktab hayoti',
            },
        ),
    ]
