# Generated by Django 5.2.1 on 2025-05-20 14:01

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoollife',
            name='description_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Tafsilot'),
        ),
        migrations.AddField(
            model_name='schoollife',
            name='description_ru',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Tafsilot'),
        ),
        migrations.AddField(
            model_name='schoollife',
            name='description_uz',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Tafsilot'),
        ),
        migrations.AddField(
            model_name='schoollife',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='schoollife',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='schoollife',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
    ]
