# Generated by Django 5.2.1 on 2026-03-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location_en',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_ru',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_uz',
        ),
        migrations.RemoveField(
            model_name='mainsettings',
            name='location_en',
        ),
        migrations.RemoveField(
            model_name='mainsettings',
            name='location_ru',
        ),
        migrations.RemoveField(
            model_name='mainsettings',
            name='location_uz',
        ),
    ]
