# Generated by Django 5.2.1 on 2026-03-14 18:48

import apps.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_event_location_en_remove_event_location_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=apps.common.fields.MiniHTMLField(blank=True, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description_en',
            field=apps.common.fields.MiniHTMLField(blank=True, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description_ru',
            field=apps.common.fields.MiniHTMLField(blank=True, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description_uz',
            field=apps.common.fields.MiniHTMLField(blank=True, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=apps.common.fields.MiniHTMLField(verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_en',
            field=apps.common.fields.MiniHTMLField(null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_ru',
            field=apps.common.fields.MiniHTMLField(null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_uz',
            field=apps.common.fields.MiniHTMLField(null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='mainsettings',
            name='short_description',
            field=apps.common.fields.MiniHTMLField(blank=True, null=True, verbose_name='Qisqa Tavsif'),
        ),
        migrations.AlterField(
            model_name='mainsettings',
            name='short_description_en',
            field=apps.common.fields.MiniHTMLField(blank=True, null=True, verbose_name='Qisqa Tavsif'),
        ),
        migrations.AlterField(
            model_name='mainsettings',
            name='short_description_ru',
            field=apps.common.fields.MiniHTMLField(blank=True, null=True, verbose_name='Qisqa Tavsif'),
        ),
        migrations.AlterField(
            model_name='mainsettings',
            name='short_description_uz',
            field=apps.common.fields.MiniHTMLField(blank=True, null=True, verbose_name='Qisqa Tavsif'),
        ),
        migrations.AlterField(
            model_name='mainsettings',
            name='title',
            field=apps.common.fields.MiniHTMLField(verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='mainsettings',
            name='title_en',
            field=apps.common.fields.MiniHTMLField(null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='mainsettings',
            name='title_ru',
            field=apps.common.fields.MiniHTMLField(null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='mainsettings',
            name='title_uz',
            field=apps.common.fields.MiniHTMLField(null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=apps.common.fields.MiniHTMLField(verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=apps.common.fields.MiniHTMLField(null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=apps.common.fields.MiniHTMLField(null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_uz',
            field=apps.common.fields.MiniHTMLField(null=True, verbose_name='Sarlavha'),
        ),
    ]
