# Generated by Django 5.2.1 on 2025-05-20 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_schoollife_description_en_schoollife_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoollife',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_lives', to='main.school', verbose_name='Maktab'),
        ),
    ]
