# Generated by Django 5.2.1 on 2025-05-21 13:29

import apps.common.utils
import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_schoollife_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner ', 'verbose_name_plural': 'Bannerlar'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu ', 'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Maktab ', 'verbose_name_plural': 'Maktablar'},
        ),
        migrations.AlterModelOptions(
            name='schoollife',
            options={'verbose_name': 'Maktab hayoti ', 'verbose_name_plural': 'Maktab hayoti'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text="Rasm 5 MB dan katta bo'lishi mumkin emas.", upload_to=apps.common.utils.generate_upload_path, validators=[apps.common.validators.file_size], verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='schoollife',
            name='image',
            field=models.ImageField(help_text="Rasm 5 MB dan katta bo'lishi mumkin emas.", upload_to=apps.common.utils.generate_upload_path, validators=[apps.common.validators.file_size], verbose_name='Rasm'),
        ),
    ]
