# Generated by Django 5.2.1 on 2025-05-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_banner_options_alter_menu_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
