# Generated by Django 5.2.1 on 2026-03-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_news_slug_alter_event_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Izoh', 'verbose_name_plural': 'Izohlar'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['order', '-start_date'], 'verbose_name': 'Tadbir', 'verbose_name_plural': 'Tadbirlar'},
        ),
        migrations.AlterModelOptions(
            name='eventmedia',
            options={'ordering': ['order'], 'verbose_name': 'Tadbir mediasi', 'verbose_name_plural': 'Tadbir medialari'},
        ),
        migrations.AlterModelOptions(
            name='eventschedule',
            options={'ordering': ['order', 'date', 'start_time'], 'verbose_name': 'Kun tartibi', 'verbose_name_plural': 'Kun tartibi'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='pastforum',
            options={'ordering': ['order'], 'verbose_name': "O'tgan forum", 'verbose_name_plural': "O'tgan forumlar"},
        ),
        migrations.AlterModelOptions(
            name='speaker',
            options={'ordering': ['order'], 'verbose_name': 'Spiker', 'verbose_name_plural': 'Spikerlar'},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['order'], 'verbose_name': 'Homiy', 'verbose_name_plural': 'Homiylar'},
        ),
        migrations.AlterModelOptions(
            name='supporter',
            options={'ordering': ['order'], 'verbose_name': "Qo'llab-quvvatlovchi", 'verbose_name_plural': "Qo'llab-quvvatlovchilar"},
        ),
        migrations.AddField(
            model_name='certificate',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='comment',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='event',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='eventmedia',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='news',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='partnerapplication',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='pastforum',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='presentationsubmission',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='supporter',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib'),
        ),
    ]
