# Generated by Django 5.2.1 on 2025-05-24 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_menu_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='main.school', verbose_name='Maktab'),
        ),
    ]
