# Generated by Django 5.2.1 on 2026-03-24 13:46

import apps.common.utils
import apps.common.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_comment_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='hero_video_file',
            field=models.FileField(blank=True, help_text='Video fayl (50 MB gacha). YouTube havolasidan ustunlik oladi.', null=True, upload_to=apps.common.utils.generate_upload_path, validators=[apps.common.validators.file_size_50], verbose_name='Hero video fayl'),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='hero_video_url',
            field=models.URLField(blank=True, help_text="YouTube video havolasi. Agar ko'rsatilsa, bosh sahifada rasm o'rniga video ko'rsatiladi.", null=True, verbose_name='Hero video havolasi (YouTube)'),
        ),
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('name', models.CharField(max_length=500, verbose_name='Nomi')),
                ('name_uz', models.CharField(max_length=500, null=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(max_length=500, null=True, verbose_name='Nomi')),
                ('name_en', models.CharField(max_length=500, null=True, verbose_name='Nomi')),
                ('type', models.CharField(choices=[('image', 'Rasm'), ('video', 'Video'), ('file', 'Fayl')], default='image', max_length=10, verbose_name='Turi')),
                ('file', models.FileField(blank=True, help_text="Fayl 50 MB dan katta bo'lishi mumkin emas.", null=True, upload_to=apps.common.utils.generate_upload_path, validators=[apps.common.validators.file_size_50], verbose_name='Fayl')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Havola')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_media', to='main.news', verbose_name='Yangilik')),
            ],
            options={
                'verbose_name': 'Yangilik mediasi',
                'verbose_name_plural': 'Yangilik medialari',
                'ordering': ['order'],
            },
        ),
    ]
