# Generated by Django 5.2.1 on 2025-05-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_menu_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='facebook_link',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook havola'),
        ),
        migrations.AlterField(
            model_name='school',
            name='instagram_link',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram havola'),
        ),
        migrations.AlterField(
            model_name='school',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Kenglik'),
        ),
        migrations.AlterField(
            model_name='school',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Uzunlik'),
        ),
        migrations.AlterField(
            model_name='school',
            name='telegram_link',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram havola'),
        ),
        migrations.AlterField(
            model_name='school',
            name='youtube_link',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube havola'),
        ),
        migrations.AlterField(
            model_name='schoollife',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tafsilot'),
        ),
        migrations.AlterField(
            model_name='schoollife',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tafsilot'),
        ),
        migrations.AlterField(
            model_name='schoollife',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tafsilot'),
        ),
        migrations.AlterField(
            model_name='schoollife',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tafsilot'),
        ),
    ]
