# Generated by Django 5.2.1 on 2026-03-24 14:39

import apps.common.utils
import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mainsettings_hero_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video_file',
            field=models.FileField(blank=True, help_text='Video fayl (50 MB gacha). YouTube havolasidan ustunlik oladi.', null=True, upload_to=apps.common.utils.generate_upload_path, validators=[apps.common.validators.file_size_50], verbose_name='Video fayl'),
        ),
        migrations.AddField(
            model_name='event',
            name='video_url',
            field=models.URLField(blank=True, help_text="YouTube video havolasi. Rasm o'rniga video ko'rsatiladi.", null=True, verbose_name='Video havolasi (YouTube)'),
        ),
    ]
