# Generated by Django 5.2.1 on 2026-03-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_event_video_file_event_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
    ]
