# Generated by Django 5.2.1 on 2025-05-27 07:06

import apps.common.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_school_facebook_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.common.mixins.SlugifyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DirectionSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('directions', models.ManyToManyField(related_name='direction_schools', to='main.direction', verbose_name="Yo'nalishlar")),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='main.school', verbose_name='Maktab')),
            ],
            options={
                'verbose_name': "Maktab yo'nalishlari ",
                'verbose_name_plural': "Maktab yo'nalishlari",
            },
            bases=(apps.common.mixins.SlugifyMixin, models.Model),
        ),
    ]
