# Generated by Django 5.2.1 on 2025-05-27 18:36

import apps.common.mixins
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_direction_directionschool'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicalInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tafsilot')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tafsilot')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Tafsilot')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Tafsilot')),
            ],
            options={
                'verbose_name': 'Musiqa instrumenti ',
                'verbose_name_plural': 'Musiqa instrumentlari',
            },
            bases=(apps.common.mixins.SlugifyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tafsilot')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tafsilot')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Tafsilot')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Tafsilot')),
            ],
            options={
                'verbose_name': 'Fan ',
                'verbose_name_plural': 'Fanlar',
            },
            bases=(apps.common.mixins.SlugifyMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'verbose_name': "Yo'nalish ", 'verbose_name_plural': "Yo'nalishlar"},
        ),
        migrations.AddField(
            model_name='direction',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Tafsilot'),
        ),
        migrations.AddField(
            model_name='direction',
            name='description_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Tafsilot'),
        ),
        migrations.AddField(
            model_name='direction',
            name='description_ru',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Tafsilot'),
        ),
        migrations.AddField(
            model_name='direction',
            name='description_uz',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Tafsilot'),
        ),
        migrations.AddField(
            model_name='direction',
            name='founded_year',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Ishga tushgan yili'),
        ),
        migrations.AddField(
            model_name='direction',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='direction',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='direction',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='direction',
            name='student_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="O'quvchilar soni"),
        ),
        migrations.AddField(
            model_name='direction',
            name='teacher_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="O'qituvchilar soni"),
        ),
        migrations.AddField(
            model_name='direction',
            name='musical_instruments',
            field=models.ManyToManyField(related_name='directions', to='main.musicalinstrument', verbose_name='Musiqa instrumentlari'),
        ),
        migrations.AddField(
            model_name='direction',
            name='subjects',
            field=models.ManyToManyField(related_name='directions', to='main.subject', verbose_name='Fanlar'),
        ),
    ]
