# Generated by Django 5.2.1 on 2025-05-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_musicalinstrument_subject_alter_direction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='musical_instruments',
            field=models.ManyToManyField(blank=True, null=True, related_name='directions', to='main.musicalinstrument', verbose_name='Musiqa instrumentlari'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, related_name='directions', to='main.subject', verbose_name='Fanlar'),
        ),
    ]
