# Generated by Django 5.2.1 on 2025-05-28 04:36

import apps.common.utils
import apps.common.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_direction_musical_instruments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicalinstrument',
            options={'verbose_name': 'Musiqa asbobi ', 'verbose_name_plural': 'Musiqa asboblari'},
        ),
        migrations.AlterField(
            model_name='direction',
            name='musical_instruments',
            field=models.ManyToManyField(blank=True, null=True, related_name='directions', to='main.musicalinstrument', verbose_name='Musiqa asboblari'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('full_name', models.CharField(max_length=500, verbose_name='F.I.O')),
                ('image', models.ImageField(help_text="Rasm 5 MB dan katta bo'lishi mumkin emas.", upload_to=apps.common.utils.generate_upload_path, validators=[apps.common.validators.file_size], verbose_name='Rasm')),
                ('experience_years', models.PositiveIntegerField(blank=True, help_text='Yil', null=True, verbose_name='Tajribasi')),
                ('directions', models.ManyToManyField(blank=True, null=True, related_name='teachers', to='main.direction', verbose_name="Yo'nalishlar")),
            ],
            options={
                'verbose_name': "O'qituvchi ",
                'verbose_name_plural': "O'qituvchilar",
            },
        ),
        migrations.CreateModel(
            name='TeacherExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('title', models.CharField(max_length=255, verbose_name='Lavozimi')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Lavozimi')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Lavozimi')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Lavozimi')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='main.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': "O'qituvchi tajribasi ",
                'verbose_name_plural': "O'qituvchi tajribalari",
            },
        ),
    ]
