# Generated by Django 5.2.1 on 2025-05-28 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_teacher_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='musical_instruments',
            field=models.ManyToManyField(blank=True, related_name='directions', to='main.musicalinstrument', verbose_name='Musiqa asboblari'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='directions', to='main.subject', verbose_name='Fanlar'),
        ),
        migrations.AlterField(
            model_name='directionschool',
            name='directions',
            field=models.ManyToManyField(blank=True, related_name='direction_schools', to='main.direction', verbose_name="Yo'nalishlar"),
        ),
        migrations.AlterField(
            model_name='directionschool',
            name='school',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='main.school', verbose_name='Maktab'),
            preserve_default=False,
        ),
    ]
