# Generated by Django 5.2.1 on 2025-05-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_direction_musical_instruments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='directions',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='main.direction', verbose_name="Yo'nalishlar"),
        ),
        migrations.AddConstraint(
            model_name='directionschool',
            constraint=models.UniqueConstraint(fields=('school',), name='unique_direction_school_per_school'),
        ),
    ]
