# Generated by Django 5.2.1 on 2025-05-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_directionschool_unique_direction_school_per_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
