# Generated by Django 5.2.1 on 2025-06-01 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_teacher_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('title', models.CharField(max_length=255, verbose_name='Savol')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Savol')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Savol')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Savol')),
                ('description', models.TextField(verbose_name='Javob')),
                ('description_uz', models.TextField(null=True, verbose_name='Javob')),
                ('description_ru', models.TextField(null=True, verbose_name='Javob')),
                ('description_en', models.TextField(null=True, verbose_name='Javob')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='main.school', verbose_name='Maktab')),
            ],
            options={
                'verbose_name': 'FAQ ',
                'verbose_name_plural': 'FAQ',
                'unique_together': {('school',)},
            },
        ),
    ]
