# Generated by Django 5.2.1 on 2025-06-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_faq_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ ', 'verbose_name_plural': 'FAQ'},
        ),
    ]
