# Generated by Django 5.2.1 on 2025-06-01 19:12

import apps.common.utils
import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_faq_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='icon',
            field=models.ImageField(blank=True, help_text="Rasm 5 MB dan katta bo'lishi mumkin emas.", null=True, upload_to=apps.common.utils.generate_upload_path, validators=[apps.common.validators.file_size], verbose_name='Ikonka'),
        ),
        migrations.AddField(
            model_name='direction',
            name='image',
            field=models.ImageField(blank=True, help_text="Rasm 5 MB dan katta bo'lishi mumkin emas.", null=True, upload_to=apps.common.utils.generate_upload_path, validators=[apps.common.validators.file_size], verbose_name='Fon rasmi'),
        ),
        migrations.AddField(
            model_name='musicalinstrument',
            name='image',
            field=models.ImageField(blank=True, help_text="Rasm 5 MB dan katta bo'lishi mumkin emas.", null=True, upload_to=apps.common.utils.generate_upload_path, validators=[apps.common.validators.file_size], verbose_name='Fon rasmi'),
        ),
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, help_text="Rasm 5 MB dan katta bo'lishi mumkin emas.", null=True, upload_to=apps.common.utils.generate_upload_path, validators=[apps.common.validators.file_size], verbose_name='Fon rasmi'),
        ),
    ]
