# Generated by Django 5.2.1 on 2025-06-01 21:22

import apps.common.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_add_image_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('title', models.CharField(max_length=255, verbose_name='Lavozim nomi')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Lavozim nomi')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Lavozim nomi')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Lavozim nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Tafsilot')),
                ('description_uz', models.TextField(null=True, verbose_name='Tafsilot')),
                ('description_ru', models.TextField(null=True, verbose_name='Tafsilot')),
                ('description_en', models.TextField(null=True, verbose_name='Tafsilot')),
                ('salary', models.CharField(blank=True, max_length=255, null=True, verbose_name='Maosh')),
                ('requirements', models.TextField(verbose_name='Talablar')),
                ('requirements_uz', models.TextField(null=True, verbose_name='Talablar')),
                ('requirements_ru', models.TextField(null=True, verbose_name='Talablar')),
                ('requirements_en', models.TextField(null=True, verbose_name='Talablar')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Joylashuv')),
                ('location_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Joylashuv')),
                ('location_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Joylashuv')),
                ('location_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Joylashuv')),
                ('type', models.CharField(choices=[('full_time', "To'la ish kuni"), ('part_time', 'Yarim ish kuni'), ('contract', 'Shartnoma asosida'), ('internship', 'Amaliyot'), ('remote', 'Masofaviy ish')], default='full_time', max_length=50, verbose_name='Ish turi')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='main.school', verbose_name='Maktab')),
            ],
            options={
                'verbose_name': "Bo'sh ish o'rni ",
                'verbose_name_plural': "Bo'sh ish o'rinlari",
                'unique_together': {('school', 'slug')},
            },
            bases=(apps.common.mixins.SlugifyMixin, models.Model),
        ),
    ]
