# Generated by Django 5.2.1 on 2025-06-01 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_add_vacancy_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Vakansiya ', 'verbose_name_plural': 'Vakansiyalar'},
        ),
    ]
