# Generated by Django 5.2.1 on 2025-06-02 07:08

import apps.common.utils
import apps.common.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_vacancy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('name', models.CharField(max_length=255, verbose_name='Kategoriya nomi')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Kategoriya nomi')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Kategoriya nomi')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Kategoriya nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tafsilot')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tafsilot')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Tafsilot')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Tafsilot')),
            ],
            options={
                'verbose_name': 'Hujjat kategoriyasi',
                'verbose_name_plural': 'Hujjat kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('title', models.CharField(max_length=255, verbose_name='Hujjat nomi')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Hujjat nomi')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Hujjat nomi')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Hujjat nomi')),
                ('file', models.FileField(help_text="Fayl 5 MB dan katta bo'lishi mumkin emas.", upload_to=apps.common.utils.generate_upload_path, validators=[apps.common.validators.file_size], verbose_name='Fayl')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.school', verbose_name='Maktab')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.documentcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
            },
        ),
    ]
