# Generated by Django 5.2.1 on 2025-06-02 07:52

import apps.common.utils
import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_documentcategory_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='documentcategory',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='documentcategory',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='documentcategory',
            name='description_uz',
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text="Fayl 50 MB dan katta bo'lishi mumkin emas.", upload_to=apps.common.utils.generate_upload_path, validators=[apps.common.validators.file_size_50], verbose_name='Fayl'),
        ),
    ]
