# Generated by Django 5.2.1 on 2025-06-12 12:22

import apps.common.utils
import apps.common.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_documentcategory_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('title', models.CharField(max_length=255, verbose_name='Sinf')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Sinf')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Sinf')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Sinf')),
                ('file', models.FileField(blank=True, help_text="Fayl 50 MB dan katta bo'lishi mumkin emas. Fayl PDF formatida bo'lishi kerak.", null=True, upload_to=apps.common.utils.generate_upload_path, validators=[apps.common.validators.file_size_50, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name="O'quv reja")),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_tables', to='main.school', verbose_name='Maktab')),
            ],
            options={
                'verbose_name': "O'quv reja",
                'verbose_name_plural': "O'quv rejalari",
            },
        ),
    ]
