# Generated by Django 5.2.1 on 2025-06-04 09:15

import apps.common.mixins
import apps.common.utils
import apps.common.validators
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_documentcategory_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('full_name', models.CharField(max_length=500, verbose_name='F.I.O')),
                ('full_name_uz', models.CharField(max_length=500, null=True, verbose_name='F.I.O')),
                ('full_name_ru', models.CharField(max_length=500, null=True, verbose_name='F.I.O')),
                ('full_name_en', models.CharField(max_length=500, null=True, verbose_name='F.I.O')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('position', models.CharField(max_length=255, verbose_name='Lavozimi')),
                ('position_uz', models.CharField(max_length=255, null=True, verbose_name='Lavozimi')),
                ('position_ru', models.CharField(max_length=255, null=True, verbose_name='Lavozimi')),
                ('position_en', models.CharField(max_length=255, null=True, verbose_name='Lavozimi')),
                ('image', models.ImageField(help_text="Rasm 5 MB dan katta bo'lishi mumkin emas.", upload_to=apps.common.utils.generate_upload_path, validators=[apps.common.validators.file_size], verbose_name='Rasm')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Tafsilot')),
                ('description_uz', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Tafsilot')),
                ('description_ru', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Tafsilot')),
                ('description_en', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Tafsilot')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon raqami')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='Instagram havola')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Telegram havola')),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='Facebook havola')),
                ('linkedin_link', models.URLField(blank=True, null=True, verbose_name='LinkedIn havola')),
                ('experience_years', models.PositiveIntegerField(blank=True, help_text='Yil', null=True, verbose_name='Tajribasi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartibi')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='main.school', verbose_name='Maktab')),
            ],
            options={
                'verbose_name': 'Rahbar ',
                'verbose_name_plural': 'Rahbarlar',
                'ordering': ['order', 'created_at'],
                'unique_together': {('school', 'slug')},
            },
            bases=(apps.common.mixins.SlugifyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('full_name', models.CharField(max_length=500, verbose_name='F.I.O')),
                ('full_name_uz', models.CharField(max_length=500, null=True, verbose_name='F.I.O')),
                ('full_name_ru', models.CharField(max_length=500, null=True, verbose_name='F.I.O')),
                ('full_name_en', models.CharField(max_length=500, null=True, verbose_name='F.I.O')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('position', models.CharField(max_length=255, verbose_name='Lavozimi')),
                ('position_uz', models.CharField(max_length=255, null=True, verbose_name='Lavozimi')),
                ('position_ru', models.CharField(max_length=255, null=True, verbose_name='Lavozimi')),
                ('position_en', models.CharField(max_length=255, null=True, verbose_name='Lavozimi')),
                ('image', models.ImageField(help_text="Rasm 5 MB dan katta bo'lishi mumkin emas.", upload_to=apps.common.utils.generate_upload_path, validators=[apps.common.validators.file_size], verbose_name='Rasm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tafsilot')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tafsilot')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Tafsilot')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Tafsilot')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon raqami')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='Instagram havola')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Telegram havola')),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='Facebook havola')),
                ('linkedin_link', models.URLField(blank=True, null=True, verbose_name='LinkedIn havola')),
                ('experience_years', models.PositiveIntegerField(blank=True, help_text='Yil', null=True, verbose_name='Tajribasi')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='main.school', verbose_name='Maktab')),
            ],
            options={
                'verbose_name': 'Xodim ',
                'verbose_name_plural': 'Xodimlar',
                'unique_together': {('school', 'slug')},
            },
            bases=(apps.common.mixins.SlugifyMixin, models.Model),
        ),
    ]
