# Generated by Django 5.2.1 on 2025-06-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_banner_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='banner',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='faq',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='leader',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='schoollife',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vacancy',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='direction',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='musicalinstrument',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AddConstraint(
            model_name='direction',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_direction_slug'),
        ),
        migrations.AddConstraint(
            model_name='leader',
            constraint=models.UniqueConstraint(fields=('school', 'slug'), name='unique_leader_school_slug'),
        ),
        migrations.AddConstraint(
            model_name='musicalinstrument',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_musicalinstrument_slug'),
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(fields=('domain',), name='unique_school_domain'),
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_school_slug'),
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.UniqueConstraint(fields=('school', 'slug'), name='unique_staff_school_slug'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_subject_slug'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('school', 'slug'), name='unique_teacher_school_slug'),
        ),
        migrations.AddConstraint(
            model_name='vacancy',
            constraint=models.UniqueConstraint(fields=('school', 'slug'), name='unique_vacancy_school_slug'),
        ),
    ]
