# Generated by Django 5.2.1 on 2025-06-13 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_timetable'),
        ('main', '0028_alter_banner_unique_together_and_more'),
    ]

    operations = [
    ]
