# Generated by Django 5.2.1 on 2025-06-18 19:17

import apps.common.mixins
import apps.common.utils
import apps.common.validators
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_document_options_alter_timetable_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='domain',
            field=models.SlugField(verbose_name='Subdomen'),
        ),
        migrations.CreateModel(
            name='Honors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.O')),
                ('full_name_uz', models.CharField(max_length=255, null=True, verbose_name='F.I.O')),
                ('full_name_ru', models.CharField(max_length=255, null=True, verbose_name='F.I.O')),
                ('full_name_en', models.CharField(max_length=255, null=True, verbose_name='F.I.O')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('type', models.CharField(choices=[('student', 'Talaba'), ('teacher', "O'qituvchi"), ('staff', 'Xodim'), ('leader', 'Rahbar')], default='student', max_length=50, verbose_name='Kim?')),
                ('description', tinymce.models.HTMLField(verbose_name='Tafsilot')),
                ('description_uz', tinymce.models.HTMLField(null=True, verbose_name='Tafsilot')),
                ('description_ru', tinymce.models.HTMLField(null=True, verbose_name='Tafsilot')),
                ('description_en', tinymce.models.HTMLField(null=True, verbose_name='Tafsilot')),
                ('image', models.ImageField(help_text="Rasm 5 MB dan katta bo'lishi mumkin emas.", upload_to=apps.common.utils.generate_upload_path, validators=[apps.common.validators.file_size], verbose_name='Rasm')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon raqami')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='honors', to='main.school', verbose_name='Maktab')),
            ],
            options={
                'verbose_name': 'Faxrimiz ',
                'verbose_name_plural': 'Faxrlarimiz',
            },
            bases=(apps.common.mixins.SlugifyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HonorAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('year', models.PositiveIntegerField(verbose_name='Yil')),
                ('description', models.TextField(verbose_name='Tafsilot')),
                ('description_uz', models.TextField(null=True, verbose_name='Tafsilot')),
                ('description_ru', models.TextField(null=True, verbose_name='Tafsilot')),
                ('description_en', models.TextField(null=True, verbose_name='Tafsilot')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('address_uz', models.CharField(max_length=255, null=True, verbose_name='Manzil')),
                ('address_ru', models.CharField(max_length=255, null=True, verbose_name='Manzil')),
                ('address_en', models.CharField(max_length=255, null=True, verbose_name='Manzil')),
                ('honor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='main.honors', verbose_name='Hojat')),
            ],
            options={
                'verbose_name': 'Yutuq ',
                'verbose_name_plural': 'Yutuqlar',
            },
        ),
        migrations.AddConstraint(
            model_name='honors',
            constraint=models.UniqueConstraint(fields=('school', 'slug'), name='unique_honors_school_slug'),
        ),
    ]
