# Generated by Django 5.2.1 on 2025-07-01 22:15

import apps.common.validators
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_school_domain_honors_honorachievements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='founded_year',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='musical_instruments',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='student_count',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='teacher_count',
        ),
        migrations.RemoveField(
            model_name='directionschool',
            name='directions',
        ),
        migrations.AddField(
            model_name='directionschool',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Tafsilot'),
        ),
        migrations.AddField(
            model_name='directionschool',
            name='description_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Tafsilot'),
        ),
        migrations.AddField(
            model_name='directionschool',
            name='description_ru',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Tafsilot'),
        ),
        migrations.AddField(
            model_name='directionschool',
            name='description_uz',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Tafsilot'),
        ),
        migrations.AddField(
            model_name='directionschool',
            name='direction',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='direction_schools', to='main.direction', verbose_name="Yo'nalish"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directionschool',
            name='founded_year',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Ishga tushgan yili'),
        ),
        migrations.AddField(
            model_name='directionschool',
            name='musical_instruments',
            field=models.ManyToManyField(blank=True, related_name='directions', to='main.musicalinstrument', verbose_name='Musiqa asboblari'),
        ),
        migrations.AddField(
            model_name='directionschool',
            name='student_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="O'quvchilar soni"),
        ),
        migrations.AddField(
            model_name='directionschool',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='directions', to='main.subject', verbose_name='Fanlar'),
        ),
        migrations.AddField(
            model_name='directionschool',
            name='teacher_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="O'qituvchilar soni"),
        ),
        migrations.AlterField(
            model_name='school',
            name='domain',
            field=models.SlugField(validators=[apps.common.validators.validate_subdomain], verbose_name='Subdomen'),
        ),
    ]
