# Generated by Django 5.2.1 on 2025-07-02 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_direction_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcategory',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_categories', to='main.school', verbose_name='Maktab'),
        ),
    ]
