# Generated by Django 5.2.1 on 2025-07-02 12:14

import apps.common.utils
import apps.common.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_documentcategory_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('image', models.ImageField(help_text="Rasm 5 MB dan katta bo'lishi mumkin emas.", upload_to=apps.common.utils.generate_upload_path, validators=[apps.common.validators.file_size], verbose_name='Rasm')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.O')),
                ('full_name_uz', models.CharField(max_length=255, null=True, verbose_name='F.I.O')),
                ('full_name_ru', models.CharField(max_length=255, null=True, verbose_name='F.I.O')),
                ('full_name_en', models.CharField(max_length=255, null=True, verbose_name='F.I.O')),
                ('rating', models.PositiveIntegerField(verbose_name='Reyting')),
                ('comment', models.TextField(verbose_name='Izoh')),
                ('comment_uz', models.TextField(null=True, verbose_name='Izoh')),
                ('comment_ru', models.TextField(null=True, verbose_name='Izoh')),
                ('comment_en', models.TextField(null=True, verbose_name='Izoh')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.school', verbose_name='Maktab')),
            ],
            options={
                'verbose_name': 'Izoh ',
                'verbose_name_plural': 'Izohlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.O')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Telefon raqami')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_forms', to='main.school', verbose_name='Maktab')),
            ],
            options={
                'verbose_name': "Foydalanuvchi so'rovi ",
                'verbose_name_plural': "Foydalanuvchi so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
