# Generated by Django 5.2.1 on 2025-07-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_comments_userform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserForm',
            new_name='ContactForm',
        ),
        migrations.AlterField(
            model_name='contactform',
            name='school',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=models.deletion.CASCADE, 
                related_name='contact_forms', 
                to='main.school', 
                verbose_name='Maktab'
            ),
        ),
    ]
