# Generated by Django 5.2.1 on 2025-07-03 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_rename_userform_to_contactform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'ordering': ['-created_at'], 'verbose_name': "Aloqa so'rovi ", 'verbose_name_plural': "Aloqa so'rovlari"},
        ),
    ]
