# Generated by Django 5.2.1 on 2025-07-09 21:36

import apps.common.utils
import apps.common.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_contactform_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'verbose_name': 'Hujjat kategoriyasi ', 'verbose_name_plural': 'Hujjat kategoriyalari'},
        ),
        migrations.CreateModel(
            name='DirectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('image', models.ImageField(help_text="Rasm 5 MB dan katta bo'lishi mumkin emas.", upload_to=apps.common.utils.generate_upload_path, validators=[apps.common.validators.file_size], verbose_name='Rasm')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_images', to='main.directionschool', verbose_name="Yo'nalish")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DirectionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('video', models.URLField(validators=[apps.common.validators.validate_youtube_link], verbose_name='Youtube video havola')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_videos', to='main.directionschool', verbose_name="Yo'nalish")),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
