# Generated by Django 5.2.1 on 2025-07-09 22:41

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_documentcategory_options_directionimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directionimage',
            options={'verbose_name': "Yo'nalish galereya ", 'verbose_name_plural': "Yo'nalish galereyalari"},
        ),
        migrations.AlterModelOptions(
            name='directionvideo',
            options={'verbose_name': "Yo'nalish video ", 'verbose_name_plural': "Yo'nalish videolar"},
        ),
        migrations.CreateModel(
            name='EduInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('description', tinymce.models.HTMLField(verbose_name='Tafsilot')),
                ('description_uz', tinymce.models.HTMLField(null=True, verbose_name='Tafsilot')),
                ('description_ru', tinymce.models.HTMLField(null=True, verbose_name='Tafsilot')),
                ('description_en', tinymce.models.HTMLField(null=True, verbose_name='Tafsilot')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edu_infos', to='main.school', verbose_name='Maktab')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
