# Generated by Django 5.2.1 on 2025-07-15 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_rename_culture_art_sitesettings_culture_arts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_settings', to='main.school', verbose_name='Maktab'),
        ),
    ]
