# Generated by Django 5.2.1 on 2025-07-16 21:25

import apps.common.utils
import apps.common.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_sitesettings_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='directionschool',
            name='direction_image',
            field=models.ImageField(blank=True, help_text="Rasm 5 MB dan katta bo'lishi mumkin emas.", null=True, upload_to=apps.common.utils.generate_upload_path, validators=[apps.common.validators.file_size], verbose_name="Yo'nalish rasmi"),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='main.subject', verbose_name="Dars o'tadigan Fan"),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Talablar'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Talablar'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Talablar'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Talablar'),
        ),
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_subscriptions', to='main.school', verbose_name='Maktab')),
            ],
            options={
                'verbose_name': 'Email obunachilar ',
                'verbose_name_plural': 'Email obunachilar',
            },
        ),
    ]
