name: Deploy Backend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # === MAIN branch deploy ===
      - name: Deploy prod
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          cd /home/xensa/digital/backend  
          git pull origin main
          docker compose -f prod.yml down
          docker compose -f prod.yml up -d --build

      # === DEV branch deploy ===
      # - name: Deploy dev
      #   if: ${{ github.ref == 'refs/heads/dev' }}
      #   run: |
      #     cd /home/xensa/digital/backend/
      #     git pull origin dev
      #     docker compose -f dev.yml down
      #     docker compose -f dev.yml up -d --build
